# Install taskfile with
# sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/go/bin

version: "3"

env:
  #K6_VERSION: v0.35.0
  XK6_K6_REPO: "/home/msv/go/src/github.com/grafana/k6" # Build from local repo 
  XK6_GETENV_VERSION: v0.0.4

silent: true

tasks:
  default:
    cmds:
      - task: test

  clean:
    desc: Clean up working directory
    cmds:
      - rm -rf k6 .task node_modules

  build:
    sources:
      - "**/*.go"
    generates:
      - k6
    cmds:
      - xk6 build --with github.com/msaf1980/xk6-carbonapi=$(pwd) --with github.com/msaf1980/xk6-getenv@${XK6_GETENV_VERSION}

  test:
    deps: [build]
    cmds:
      - ./k6 run --no-color --no-usage-report tests/test.js
